name: Primer WorkFlow

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: |
          echo "Ejecutando el primer msg del workflow"
      - name: Dime la fecha
        run: date
      - run: ls -l