name: Build on Push

on:
    push:
        paths-ignore:
            -   ".github/**"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v1
            -   name: Build
                env:
                    NETLIFY_SITE_ID: ${{  secrets.NETLIFY_SITE_ID  }}
                    NETLIFY_AUTH_TOKEN: ${{  secrets.NETLIFY_AUT_TOKEN  }}
                run:    |
                    npm
                    npm start
                    npx netlify-cli deploy --dir=dist --prod