name: Deplyment Pipeline

on:
    push:
        branches:
            -   main

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: '21'
            -   name: Install Dependencies
                run: npm ci
            -   name: Deploy to Heroku
                uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
                with:
                    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                    heroku_app_name: ${{secrets.HEROKU_APP}}
                    heroku_email: ${{secrets.HEROKU_API_EMAIL}}